---
- name: Ensure tzdata is installed
  ansible.builtin.apt:
    name: tzdata
    state: present
  become: true

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"
  become: true

- name: Configure NTP servers
  ansible.builtin.template:
    src: timesyncd.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart systemd-timesyncd

- name: Start and enable NTP service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  become: true
