---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install common utilities
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - net-tools
      - unzip
      - tar
      - bash-completion
      - fail2ban
      - nfs-common
      - zsh
      - qemu-guest-agent
    state: present
  become: true
